version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆ "
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 7
      exclude:
        - "navikt/sykepenger-github-workflows*"

  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 7
